name: ci-wf-test
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  build-and-test:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: 
      # кеширование для npm
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      # установка и тесты приложения ci-app
      - run: npm ci
      - run: make test
      - run: make lint
      # SNYK анализ на уязвимости
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
